// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAnpVM071CIrloicFOPwu9tJWe9YZfSA',
    appId: '1:454557283675:web:559916c17bab477dbbd67e',
    messagingSenderId: '454557283675',
    projectId: 'gestion360-e1070',
    authDomain: 'gestion360-e1070.firebaseapp.com',
    storageBucket: 'gestion360-e1070.firebasestorage.app',
    measurementId: 'G-85GT7PW8DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALzsmDRCRlBo10iXOzfHTuu-5_Tt4tNkw',
    appId: '1:454557283675:android:d9a90de9e7c1bdb8bbd67e',
    messagingSenderId: '454557283675',
    projectId: 'gestion360-e1070',
    storageBucket: 'gestion360-e1070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdj2guxIU91XeoYXWRBGQ3Ya6Q93OCd_8',
    appId: '1:454557283675:ios:7ff21dfddbc030cabbd67e',
    messagingSenderId: '454557283675',
    projectId: 'gestion360-e1070',
    storageBucket: 'gestion360-e1070.firebasestorage.app',
    iosClientId: '454557283675-ul95nu1j4866hke5ukjml439irur75ag.apps.googleusercontent.com',
    iosBundleId: 'com.alpinca.gestion360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdj2guxIU91XeoYXWRBGQ3Ya6Q93OCd_8',
    appId: '1:454557283675:ios:7ff21dfddbc030cabbd67e',
    messagingSenderId: '454557283675',
    projectId: 'gestion360-e1070',
    storageBucket: 'gestion360-e1070.firebasestorage.app',
    iosClientId: '454557283675-ul95nu1j4866hke5ukjml439irur75ag.apps.googleusercontent.com',
    iosBundleId: 'com.alpinca.gestion360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdXObSmaAFJJj8Sx0STSvefSexz91sh3g',
    appId: '1:454557283675:web:3415a633121d88dcbbd67e',
    messagingSenderId: '454557283675',
    projectId: 'gestion360-e1070',
    authDomain: 'gestion360-e1070.firebaseapp.com',
    storageBucket: 'gestion360-e1070.firebasestorage.app',
    measurementId: 'G-ZC0751D1ZX',
  );
}
